# Generated by Django 3.1 on 2022-12-19 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_auto_20221218_0023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='product',
            field=models.IntegerField(default=0),
        ),
    ]
