# Generated by Django 3.1 on 2022-12-19 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0003_auto_20221219_1007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='product',
        ),
        migrations.AddField(
            model_name='user',
            name='CVV',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='user',
            name='Expiration',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='user',
            name='cardname',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='user',
            name='cardnum',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='user',
            name='productnum',
            field=models.TextField(default=''),
        ),
    ]
